dist: focal
language: php

matrix:
    include:
        - php: 7.4
        - php: 8.0
        - php: 8.1
        - php: 8.2
        - php: nightly
    fast_finish: true
    allow_failures:
        - php: nightly

before_script:
  - composer update --prefer-dist --no-interaction $COMPOSER_FLAGS

script:
  - ./vendor/bin/phpunit -v -c phpunit.xml.dist
  - if [[ "$PHP_VERSION" != "nightly" ]]; then ./vendor/bin/phpmd src/ text phpmd.xml.dist; fi
  - if [[ "$PHP_VERSION" != "nightly" ]]; then vendor/bin/php-cs-fixer fix --config=.php_cs.dist -v --dry-run --stop-on-violation --using-cache=no; fi

cache:
  directories:
    - $HOME/.composer/cache
